-- Project Off The Books · seed teams + members from the /config JSON.
-- Generated from config/teams.json + config/roster.json. Run AFTER 0004.
-- Idempotent: re-running upserts the same rows (safe to run again after edits to
-- the JSON). NOTE: this OVERWRITES name/color/team/clues for these ids back to
-- the JSON values, so don't re-run it if you've since edited people in the panel
-- and want to keep those edits.

-- teams
insert into public.teams (id, name, color, sort_order) values ('team1', 'Team 1', '#2f6bff', 0)
  on conflict (id) do update set name = excluded.name, color = excluded.color, sort_order = excluded.sort_order, updated_at = now();
insert into public.teams (id, name, color, sort_order) values ('team2', 'Team 2', '#e0a436', 1)
  on conflict (id) do update set name = excluded.name, color = excluded.color, sort_order = excluded.sort_order, updated_at = now();
insert into public.teams (id, name, color, sort_order) values ('team3', 'Team 3', '#16a34a', 2)
  on conflict (id) do update set name = excluded.name, color = excluded.color, sort_order = excluded.sort_order, updated_at = now();
insert into public.teams (id, name, color, sort_order) values ('team4', 'Team 4', '#db2777', 3)
  on conflict (id) do update set name = excluded.name, color = excluded.color, sort_order = excluded.sort_order, updated_at = now();
insert into public.teams (id, name, color, sort_order) values ('team5', 'Team 5', '#7c3aed', 4)
  on conflict (id) do update set name = excluded.name, color = excluded.color, sort_order = excluded.sort_order, updated_at = now();
insert into public.teams (id, name, color, sort_order) values ('team6', 'Team 6', '#0891b2', 5)
  on conflict (id) do update set name = excluded.name, color = excluded.color, sort_order = excluded.sort_order, updated_at = now();
insert into public.teams (id, name, color, sort_order) values ('team7', 'Team 7', '#ea580c', 6)
  on conflict (id) do update set name = excluded.name, color = excluded.color, sort_order = excluded.sort_order, updated_at = now();
insert into public.teams (id, name, color, sort_order) values ('team8', 'Team 8', '#4f46e5', 7)
  on conflict (id) do update set name = excluded.name, color = excluded.color, sort_order = excluded.sort_order, updated_at = now();
insert into public.teams (id, name, color, sort_order) values ('demo', 'Demo Team', '#0d9488', 8)
  on conflict (id) do update set name = excluded.name, color = excluded.color, sort_order = excluded.sort_order, updated_at = now();

-- members
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('ganesh.somvanshi', 'ganesh.somvanshi@verveadvisory.com', 'Ganesh Somvanshi', 'team1', true, 0, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('aditi.jain', 'aditi.jain@verveadvisory.com', 'Aditi Jain', 'team1', false, 1, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('palash.somani', 'palash.somani@verveadvisory.com', 'Palash Somani', 'team1', false, 2, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('mayank.panchal', 'mayank.panchal@verveadvisory.com', 'Mayank Panchal', 'team1', false, 3, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('vaishali.malasi', 'vaishali.malasi@verveadvisory.com', 'Vaishali Malasi', 'team1', false, 4, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('viren.sunil.khetani', 'viren.khetani@verveadvisory.com', 'Viren Sunil Khetani', 'team1', false, 5, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('tarun.ghumnani', 'tarun.ghumnani@verveadvisory.com', 'Tarun Ghumnani', 'team1', false, 6, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('ayush.ghumnani', 'ayush.ghumnani@verveadvisory.com', 'Ayush Ghumnani', 'team1', false, 7, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('ritesh.dilip.chaudhari', 'ritesh.chaudhari@verveadvisory.com', 'Ritesh Dilip Chaudhari', 'team1', false, 8, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('sakshi.desai', 'sakshi.desai@verveadvisory.com', 'Sakshi Desai', 'team1', false, 9, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('laxmi.khandelwal', 'laxmi.khandelwal@verveadvisory.com', 'Laxmi Khandelwal', 'team2', true, 0, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('reena.agrawal', 'reena.agrawal@verveadvisory.com', 'Reena Agrawal', 'team2', false, 1, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('aman.jalan', 'aman.jalan@verveadvisory.com', 'Aman Jalan', 'team2', false, 2, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('tanvi.agrawal', 'tanvi.agrawal@verveadvisory.com', 'Tanvi Agrawal', 'team2', false, 3, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('sumair', 'sumair.sadiq@verveadvisory.com', 'Sumair Sadiq', 'team2', false, 4, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('rohan.patil', 'rohan.patil@verveadvisory.com', 'Rohan Patil', 'team2', false, 5, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('akshata.kolekar', 'akashata.kolekar@verveadvisory.com', 'Akshata Kolekar', 'team2', false, 6, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('pushpa.mourya', 'pushpa.mourya@verveadvisory.com', 'Pushpa Mourya', 'team2', false, 7, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('asmita.sanjay.lawate', 'asmita.lawate@verveadvisory.com', 'Asmita Sanjay Lawate', 'team2', false, 8, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('balaji.prabhu.shinde', 'balaji.shinde@verveadvisory.com', 'Balaji Prabhu Shinde', 'team2', false, 9, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('neethu', 'Neethu.george@verveadvisory.com', 'Neethu George', 'team2', false, 10, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('krutanjali.patil', 'krutanjali.patil@verveadvisory.com', 'Krutanjali Patil', 'team3', true, 0, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('fiza.rizvi', 'fiza.rizvi@verveadvisory.com', 'Fiza Rizvi', 'team3', false, 1, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('shubham.kothari', 'shubham.kothari@verveadvisory.com', 'Shubham Kothari', 'team3', false, 2, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('vaishnavee.kalantri', 'vaishnavee.kalantri@verveadvisory.com', 'Vaishnavee Kalantri', 'team3', false, 3, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('radhika.rathi', 'radhika.rathi@verveadvisory.com', 'Radhika Rathi', 'team3', false, 4, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('sayam.doshi', 'sayam.doshi@verveadvisory.com', 'Sayam Doshi', 'team3', false, 5, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('amol.bibwe', 'amol.bibwe@verveadvisory.com', 'Amol Bibwe', 'team3', false, 6, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('abhishek.sonar', 'abhishek.sonar@verveadvisory.com', 'Abhishek Sonar', 'team3', false, 7, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('vishakha.jat', 'vishakha.jat@verveadvisory.com', 'Vishakha Jat', 'team3', false, 8, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('prem.duseja', 'prem.duseja@verveadvisory.com', 'Prem Duseja', 'team4', true, 0, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('sima.jain', 'sima.jain@verveadvisory.com', 'Sima Jain', 'team4', false, 1, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('pranay.oswal', 'consultant.accounts@verveadvisory.com', 'Pranay Oswal', 'team4', false, 2, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('kajal.kale', 'kajal.kale@verveadvisory.com', 'Kajal Kale', 'team4', false, 3, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('ansari.matiullah.ziyaullah', 'Ansari.Mutiullah@verveadvisory.com', 'Ansari Matiullah Ziyaullah', 'team4', false, 4, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('aditya.agrawal', 'aditya.agrawal@verveadvisory.com', 'Aditya Agrawal', 'team4', false, 5, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('shubham.dhanawade', 'shubham.dhanawade@verveadvisory.com', 'Shubham Dhanawade', 'team4', false, 6, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('prashant.sir', 'prashant.joshi@verveadvisory.com', 'Prashant Joshi', 'team4', false, 7, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('komal.kere', 'komal.kere@verveadvisory.com', 'Komal Kere', 'team4', false, 8, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('muskan.daswani', 'muskan.daswani@verveadvisory.com', 'Muskan Daswani', 'team4', false, 9, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('shweta.ghumnani', 'shweta.ghumnani@verveadvisory.com', 'Shweta Ghumnani', 'team5', true, 0, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('namrata.patil', 'namrata.patil@verveadvisory.com', 'Namrata Gajanan Patil', 'team5', false, 1, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('vidhi.khandelwal', 'vidhi.khandelwal@verveadvisory.com', 'Vidhi Khandelwal', 'team5', false, 2, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('mansavi.more', 'manasvi.more@verveadvisory.com', 'Manasvi More', 'team5', false, 3, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('shrikar.moolya', 'shrikar.moolya@verveadvisory.com', 'Shrikar Moolya', 'team5', false, 4, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('meenal.suke', 'meenal.suke@verveadvisory.com', 'Meenal Suke', 'team5', false, 5, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('preet.khandelwal', 'preet.khandelwal@verveadvisory.com', 'Preet Khandelwal', 'team5', false, 6, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('mahadev.thawani', 'mahadev.thawani@verveadvisory.com', 'Mahadev Thawani', 'team5', false, 7, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('harshita.rajput', 'harshita.rajput@verveadvisory.com', 'Harshita Rajput', 'team5', false, 8, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('arya.magar', 'arya.magar@verveadvisory.com', 'Arya Magar', 'team5', false, 9, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('harsh.jain', 'harsh.jain@verveadvisory.com', 'Harsh Jain', 'team6', true, 0, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('avani.vijay', 'avani.vijay@verveadvisory.com', 'Avani Vijay', 'team6', false, 1, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('priyanka.mantri', 'priyanka.mantri@verveadvisory.com', 'Priyanka Mantri', 'team6', false, 2, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('aditi.singh', 'aditi.singh@verveadvisory.com', 'Aditi Singh', 'team6', false, 3, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('sakshi.ghodke', 'sakshi.ghodke@verveadvisory.com', 'Sakshi Bharat Ghodke', 'team6', false, 4, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('harsha.rajput', 'harsha.rajput@verveadvisory.com', 'Harsha Rajput', 'team6', false, 5, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('gagandeep.singh', 'gagandeep.singh@verveadvisory.com', 'Gagandeep Singh', 'team6', false, 6, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('debarima.paul', 'debarima.paul@verveadvisory.com', 'Debarima Paul', 'team6', false, 7, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('rukaiya.rangoonwala', 'rukaiya.rangoonwala@verveadvisory.com', 'Rukaiya Rangoonwala', 'team7', true, 0, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('ronit.dilip.jadhav', 'ronit.jadhav@verveadvisory.com', 'Ronit Dilip Jadhav', 'team7', false, 1, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('vikaram.bhist', 'vikramsingh.bisht@verveadvisory.com', 'Vikram Bisht', 'team7', false, 2, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('shashank.channawar', 'shashank.channawar@verveadvisory.com', 'Shashank Channawar', 'team7', false, 3, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('harshvardhan.patil', 'harshvardhan.patil@verveadvisory.com', 'Harshvardhan Patil', 'team7', false, 4, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('trinath.kethavath', 'trinath.kethav@verveadvisory.com', 'Trinath Kethavath', 'team7', false, 5, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('shubhangi', 'Shubhangi.Madhikar@verveadvisory.com', 'Shubhangi Ganesh Madhikar', 'team7', false, 6, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('kajal.yadav', 'kajal.yadav@verveadvisory.com', 'Kajal Yadav', 'team7', false, 7, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('aastha.chandwani', 'aashta.chandwani@verveadvisory.com', 'Aastha Chandwani', 'team7', false, 8, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('anjali.yadav', 'anjali.yadav@verveadvisory.com', 'Anjali Yadav', 'team8', true, 0, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('pratik.nilakhe', 'pratik.nilakhe@verveadvisory.com', 'Pratik Nilakhe', 'team8', false, 1, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('vidya.khandelwal', 'vidya.khandelwal@verveadvisory.com', 'Vidya Khandelwal', 'team8', false, 2, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('atharv.kale', 'atharv.kale@verveadvisory.com', 'Atharv Kale', 'team8', false, 3, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('shailesh.chavan', 'shailesh.chavan@verveadvisory.com', 'Shailesh Chavan', 'team8', false, 4, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('rajvir.arya', 'rajvir.arya@verveadvisory.com', 'Rajvir Arya', 'team8', false, 5, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('rajat.sonkar', 'rajat.sonkar@verveadvisory.com', 'Rajat Sonkar', 'team8', false, 6, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('pooja.mahto', 'pooja.mahto@verveadvisory.com', 'Pooja Mahto', 'team8', false, 7, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('om.anil.bhombe', 'om.bhombe@verveadvisory.com', 'Om Anil Bhombe', 'team8', false, 8, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('aman.paul', 'aman.paul@verveadvisory.com', 'Aman Paul', null, false, 0, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('tushar.gurnani', 'tushar.gurnani@verveadvisory.com', 'Tushar Kumar Gurnani', null, false, 0, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('akshay.deshmukh', 'akshay.deshmukh@infrabeat.com', 'Akshay Deshmukh', null, false, 0, null, '{"hobbies":[],"quirks":[],"funFacts":[]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('satyam.rathi', 'satyam.rathi@verveadvisory.com', 'Satyam Rathi', 'demo', false, 0, array['devendra.mandhana','harshal.pahade']::text[], '{"hobbies":[],"quirks":[],"funFacts":["Clue X"]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('sakshi.barwal', 'sakshi.barwal@verveadvisory.com', 'Sakshi Barwal', 'demo', false, 1, array['harshal.pahade','priya.agrawal']::text[], '{"hobbies":[],"quirks":[],"funFacts":["Clue Y"]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('harshal.pahade', 'harshal.pahade@verveadvisory.com', 'Harshal Pahade', 'demo', false, 2, array['sayli.sonone','sakshi.barwal']::text[], '{"hobbies":[],"quirks":[],"funFacts":["Clue Z"]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('devendra.mandhana', 'devendra.mandhana@verveadvisory.com', 'Devendra Mandhana', 'demo', false, 3, array['satyam.rathi','sakshi.barwal']::text[], '{"hobbies":[],"quirks":[],"funFacts":["Clue A"]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('priya.agrawal', 'priya.agrawal@verveadvisory.com', 'Priya Agrawal', 'demo', false, 4, array['sakshi.barwal','sakshi.jadav']::text[], '{"hobbies":[],"quirks":[],"funFacts":["Clue B"]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('sakshi.jadav', 'sakshi.jadav@verveadvisory.com', 'Sakshi Jadav', 'demo', false, 5, array['priya.agrawal','sayli.sonone']::text[], '{"hobbies":[],"quirks":[],"funFacts":["Clue C"]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
insert into public.members (id, email, display_name, team_id, is_manager, sort_order, guess_targets, clues) values ('sayli.sonone', 'sayli.sonone@verveadvisory.com', 'Sayli Sonone', 'demo', false, 6, array['sakshi.jadav','harshal.pahade']::text[], '{"hobbies":[],"quirks":[],"funFacts":["Clue D"]}'::jsonb)
  on conflict (id) do update set email = excluded.email, display_name = excluded.display_name, team_id = excluded.team_id, is_manager = excluded.is_manager, sort_order = excluded.sort_order, guess_targets = excluded.guess_targets, clues = excluded.clues, updated_at = now();
